---
title: "R Notebook"
output: html_notebook
---

Förstå (förklara) - predicera

hypotesprövning (noll-hypotes: ingen effekt/skillnad/påverkan)
1. Permutations- och ranktest. Parameterfritt. Ingen modell. P-värden och test.
2. Statistisk modell. Underliggande teori.

2 => 1 (Kan jämföra grupper via effektestmiat från modell).


# Modellering

Söker $\hat f$ sådan att 

$$Y = f(X) = \hat f (X) + \varepsilon \approx \hat f (X)$$

för $X = X_1, X_2, \dots, X_p$ oberoende variabler och $Y$ beroende.
$Y$ i detta fall kan även vara t ex sannolikheten för ett utfall (logistisk regression).


# Viktiga modelleringssteg

1. Teori om lämplig modell (LM, GLM, Cox)
2. Val av inkluderade oberoende variabler
3. Skattning av dessa variabler
4. Undersök modellanpassning


# Regression

Ofta "regression to the mean" (men även kvantiler inkl median möjlig).

- Linjär (LM): $f = \beta X$
- Generaliserad linjär (GLM) $f = g(\beta X)$ för funktion $g$
  - Logistisk regression
- Cox ($\lambda e^{\beta X}$)
- (Additiva modeller, mixade/hierarkiska modeller etc ...)

Vi utgår här från linjär regression men det mesta är generaliserbart.



# Enkel/multipel

- Enkel/univariabel = en oberoende variabel: $X = X_1$
- Multipel/multivariabel = fler oberoende variabler: $X = X_1, \dots, X_p$

Ej att förväxla med:

- Univariat = en utfallsvariabel: $Y = Y_1$
- Multivariat = flera utfallsvariabler: $Y = Y_1, \dots, Y_{p'}$


# Frågeställning

Vad är den kliniska frågeställningen?
Detta bör tänkas igenom noggrant innan analysen påbörjas!

T ex: Hur mår man efter en höftprotesoperation?

Kan vi besvara frågan med den data vi har?
Nja, vi kanske behöver specificera frågan lite.

T ex: Hur upplever patienter sin generella hälsa ett år efter höftprotesoperation?

Kan vi besvara denna fråga?
Ja, mha EQ-VAS från PROM-formulär ett år postoperativt (`vas1`).


# Typ av modell

På vilken skala mäts utfallet?

Approximativt kontinuerligt t o m 2016 (därefter på ordinalskala).

I detta fall blir LM lämpligt!



# Exposure/treatment

Vilka grupper/vilka behandlingar vill vi jämföra?
Detta bör också tänkas igenom noga före analysen.
Kanske bestäms detta t o m före utfallet.

T ex: Hur skiljer sig gamla från unga?

Har vi denna information?
Nja, inte "ung" vs "gammal" men väl ålder vid operation (`age`).

Detta är en approximativt kontinuerlig variabel. 
Ibland finns skäl till kategorisering, men undvik om så inte är fallet! 


# Confounders

Vilka ytterligare variabler kan tänkas påverka utfallet?

Denna frågeställning är ofta inte lika väl genomtänkt före analysstart.
DAG?

Ska vi ta med

- kön (`sex`)
- preoperativ hälsa (`vas0`)
- födelseår (`byear`)
- Om första bokstaven i sjukhusnamnet där operationen ägde rum var en hård vokal (`hardvok1sjname`).
- Elektiva vs akuta (`dia`)

- Ja, "bra att ha" (t ex krav för Sveriges officiella statistik)
- Ja, ty har sannolikt en signifikant påverkan
- Kanske, ty för en längre studieperiod riskerar vi annars blanda ihop ålder och kohort
- Nej, även om detta skulle falla ut signifikant riskeras overfittnig.
- Nej, detta blir snarast en variabel för stratifiering eller i vårt fall exklusion (ty frakturer saknar `vas0`)


# Variabeltransformationer

- kön blir faktorvariabel: `sex = 1` för män och `sex = 0` för kvinnor
- Kanske vill vi logaritmera `vas0` (men kanske i så fall även `vas1`)
- Kanske är inte det exakta fördelseåret intressant utan snarare en kategorisering av "baby-boomers", "ironiska generationen", "millenials" etc. I så fall en ordinal variabel med flera dummy-variabler i modellen.

??? 
Kanske snarare operationsåret än födelseåret?


# Parameterskattning

Vi låter detta vara en black-box, "dator-trolleri".

- minsta kvadratmetoden
- maximum likelihood
- icke-linjär minsta kvadratmetod



# Exkludera variabler

Den skattade modellen bör vara av intresse för att förstå hur oberoende och beroende variabler hänger ihpo (även för variabler som inte är "signifikanta").

Söker vi en så enkel modell som möjligt kan vi dock prova att exkludera vissa av de utvalda variablerna.

- Nestade modeller, AIC, BIC
- Step-wise backward/forward selection



# Undvik

- Inklusion av icke motiverade variabler
- Interaktionseffekter utan main effects
- Overfitting
- Korrelerade oberoende variabler (om syftet är att förstå/skatta effekter)
- Extrapolation


# Interaktion 

Exempel med linjär modell (men generaliserbart).

Endast huvudeffekterer (main effects): 
$$f(X) = \sum X_i \beta_i$$

Huvudeffekter + interaktionseffekter: 
$$f(X) = \sum X_i \beta_i + \sum \sum X_i X_j \beta_{ij}$$

Interaktioner mellan fler variabler ($\beta \cdot \prod X_k$), samt transformationer av dessa är teoretiskt möjligt men blir svårtolkat.


# Tolkning av interaktionseffekter

- Svårt
- Marginaleffekter
- Inkludera alltid main effects för korresponderande interaktionseffekter
- Hur hanteras omöjliga kombinationer (t ex gravida män, cementerad cup för halvprotes eller slutenvård på vårdcentral)?


